version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /beforeinstall.sh
      timeout: 300
      runas: root
    - location: /startserver.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /stopserver.sh
      timeout: 300
      runas: root 
